name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    branches: [ fix-publish-ci ]
    tags:
      - 'v*'
jobs:

  build_rust_libs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
        java: [8, 11, 15, 16]
    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Publish package
        run: ./gradlew rust-deploy

      - name: "Upload Rust Static lib for ${{matrix.os}} for java - ${{matrix.java}}"
        uses: actions/upload-artifact@v2
        with:
          name: "${{matrix.os}}-${{matrix.java}}"
          path: ./fluvio/libs/
          retention-days: 5


  publish:
    runs-on: [ubuntu-latest]
    needs: [build_rust_libs]
    strategy:
      matrix:
        # better work around.
        java: [8, 11, 15, 16]
    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Download linux.index.node
        uses: actions/download-artifact@v2
        with:
          name: "ubuntu-latest-${{matrix.java}}"
          path: ./fluvio/libs/

      - name: Download linux.index.node
        uses: actions/download-artifact@v2
        with:
          name: "macos-latest-${{matrix.java}}"
          path: ./fluvio/libs/

      - name: Publish package
        run: make publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
